id: IB406B6A3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:36:04+00:00'
last_modified: '2022-06-08T05:21:30.862660+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01602
  title: འཕགས་པ་མཚན་ཡང་དག་པར་བརྗོད་པའི་མཚན་གྱི་སྔགས་དོན་གཟིགས་པའི་རྣམ་པར་བཤད་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9CCC:
      image_group_id: I00KG02840
      title: Volume 1 of 'phags pa mtshan yang dag par brjod pa'i mtshan gyi sngags
        don gzigs pa'i rnam par bshad pa
      total_pages: 194
      order: 1
      base_file: 9CCC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
